language: go
sudo: required

env:
  global:
    - DEP_VERSION="0.4.1"
    - DOCKER_IMAGE="materkov/diffcalculator"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

services:
  - docker

script:
  - go build -o /app cmd/main.go

after_success:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build . -t $DOCKER_IMAGE:$TRAVIS_COMMIT
  - docker push $DOCKER_IMAGE:$TRAVIS_COMMIT
